### ISSUE TITLE
Working on Data Visualization using Matplotlib

### ISSUE THREAD

**Issue by Lawrence-Krukrubo** [odpi/OpenDS4All#96]
Hello,

I'm working on an intermediate course on the above topic.

I have two questions.

1.  The minimum number of slides per module is 30. What is the maximum number of slides?

2. Can I create a module in parts or series, such as **DATA-VISUALIZATION-With-Matplotlib-Part1-intermediate.md**, for example?

**Comment by Frenchhorn005** [comment]
Hi Lawrence,

Regarding your questions: 

1. Two thinks to keep in mind. We are aiming for chunks of 50 minute lectures, so too many slides will need many lectures
to cover and it my be unrealistic to expect a faculty member to devote so much time to a particular topic if this is taught as part of a Data Science course. Also the PowerPoint files get very large quickly and this may create issues with storage and being able to successfully and quickly download files. So to avoid any technical issues we do not want the PowerPoint files to be too big. 60 slides is about the maximum we have for any lesson at the moment and that seems like a "soft" upper limit.
2. The OpenDS4All modules can be "mixed and matched" at the discretion of the instructor, according to preferences, time constraints, and the target audience. To allow this to happened we are trying to limit the dependencies of modules on other modules. So we would rather suggest to try and make the modules/lessons independent so that it is easier to mix and match. Perhaps more introductory visualizations in one lesson and more complex visualizations requiring some extra code or the artist layer instead of the scripting layer in a second lesson.

Regards,
Andre

**Comment by Lawrence-Krukrubo** [comment]
Okay thanks @Andre.
I get it better now.
